[package]
name = "pdf-rendering-srv"
version = "0.1.4"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1.47.1", features = ["macros", "rt-multi-thread", "rt", "full"] }
prost = "0.14.1"
headless_chrome = "1.0.18"
tonic = "0.14.2"
tonic-prost = "0.14.2"
tonic-prost-build = "0.14.2"
prost-types = "0.14.1"
tokio-stream = "0.1.17"
tiny_http = "0.12.0"
tonic-reflection = "0.14.2"
tonic-health = "0.14.2"
anyhow = "1.0.100"
log = "0.4.28"
env_logger = "0.11.8"
config = "0.15.17"
aws-sdk-s3 = "1.106.0"
aws-sdk-config = "1.89.0"
aws-smithy-runtime-api = "1.9.0"
lopdf = "0.38.0"
serde_json = "1.0.145"
serde = { version = "1.0.228", features = ["derive"] }
prost-wkt-types = "0.7.0"
ulid = "1.2.1"

[build-dependencies]
tonic-build = "0.14.2"
tonic-prost-build = "0.14.2"
reqwest = { version = "0.12.23", features = ["blocking", "json"] }
flate2 = "1.1.2"
tar = "0.4.44"
