[package]
name = "pdf-rendering-srv"
version = "0.1.5"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1.53.1", features = ["macros", "rt-multi-thread", "rt", "full"] }
prost = "0.14.4"
headless_chrome = "1.0.22"
tonic = "0.14.6"
tonic-prost = "0.14.6"
tonic-prost-build = "0.14.6"
prost-types = "0.14.4"
tokio-stream = "0.1.19"
tiny_http = "0.12.0"
tonic-reflection = "0.14.6"
tonic-health = "0.14.6"
anyhow = "1.0.104"
log = "0.4.34"
env_logger = "0.11.11"
config = "0.15.27"
aws-sdk-s3 = "1.151.0"
aws-sdk-config = "1.125.0"
aws-smithy-runtime-api = "1.19.0"
lopdf = "0.45.0"
serde_json = "1.0.151"
serde = { version = "1.0.229", features = ["derive"] }
prost-wkt-types = "0.7.2"
ulid = "3.0.0"

[build-dependencies]
tonic-build = "0.14.6"
tonic-prost-build = "0.14.6"
reqwest = { version = "0.13.5", features = ["blocking", "json"] }
flate2 = "1.1.10"
tar = "0.4.46"
