= PDF Rendering Service

A Docker image for rendering PDFs from HTML.

[#features]
== Features

* Good for receipts, invoices, or any other content.
* It uses the https://github.com/alpeware/chrome-headless-trunk[`chrome-headless-trunk`]
as base image for Chrome and packages the https://github.com/alvarcarto/url-to-pdf-api[`url-to-pdf-api`]
library to form a solid and easy-to-use microservice.

**Note**: currently restore and reset is not implemented.The image is available on
https://hub.docker.com/repository/docker/restorecommerce/pdf-rendering-srv[`docker hub`].

[#configuration]
== Configuration

[#configuration_install_extra_fonts]
=== Installing Extra Fonts

When text is rendered by a computer, sometimes characters are displayed as 口 a.k.a “tofu”.
They are little boxes to indicate your device does not have a font to display the text.
To solve this additional fonts can be installed with in the container:

[source,sh]
----
docker exec -it restorecommerce_pdf_rendering_srv /bin/bash
apt-get update
apt-get install -yq fonts-symbola      # 🙄🙄🙄
apt-get install -yq fonts-noto-cjk     # 囍, 언문, にほんご
apt-get install -yq fonts-ocr-b        # PASSPORT FONT
----


[#usage]
== Usage

[#usage_with_url]
=== With URL

[source,sh]
----
curl -o google.pdf -XGET localhost:9000/api/render?url=http://google.com

----

[#usage_with_html_file]
=== With HTML File

[source,sh]
----
curl -o index.pdf -XPOST -d@index.html -H 'content-type: text/html' 'localhost:9000/api/render'

----

[#usage_with_pdf_options]
=== With PDF Options

The service supports sll https://github.com/alvarcarto/url-to-pdf-api#get-apirender[`options`] provided by which can be passed as query
parameters:

[source,sh]
----
curl -o index.pdf -XPOST -d@index.html -H 'content-type: text/html' 'localhost:9000/api/render?pdf.margin.top=100px&pdf.margin.bottom=100px&pdf.displayHeaderFooter=true&pdf.footerTemplate=%3Cdiv%20style=%22width:100%25%22%3E%3Cp%20style=%22padding-right:1cm;text-align:right;font-size:10px;%20%22%3Epage%20%3Cspan%20class=%22pageNumber%22%3E%3C/span%3E%20of%20%3Cspan%20class=%22totalPages%22%3E%3C/p%3E'
----
[#usage_with_api_key]
=== With API Key

The optional `X-API-KEY` can be used for authentication and can be set using `API_TOKENS` environment variable when running the container.

[source,sh]
----
curl -o google.pdf -H 'X-API-KEY: XXXXXX' -XGET localhost:9000/api/render?url=http://google.com
----
