= PDF Rendering Service

A microservice for rendering PDFs from HTML using the Chromium browser.

[#features]
== Features

* Good for any kind of content like receipts, invoices, reports.
* gRPC interface including health checks.
* Batch rendering.
* Return or upload render results to an S3 endpoint.
* Uses link:https://www.chromium.org/[Chromium] to render PDF.
* Supports various fonts out of the box and adding custom fonts.

[#example]
== Example

[source,html]
----
<!DOCTYPE html>
<html>
<body>

<p style="font-family:Liberation">This is a paragraph - Liberation.</p>
<p style="font-family:Liberation Sans">This is a paragraph - Liberation Sans.</p>
<p style="font-family:Noto Serif">This is a paragraph - Noto Serif.</p>
<p style="font-family:Noto Sans">This is a paragraph - Noto Sans.</p>
<p style="font-family:Arial">This is a paragraph - Arial (without font being installed).</p>
<p style="font-family:Comic Sans MS">This is a paragraph - Comic Sans MS (without font being installed).</p>
<p style="font-family:Times New Roman">This is a paragraph - Times New Roman (without font being installed).</p>

</body>
</html>
----

renders like this in PDF:
link:https://github.com/restorecommerce/pdf-rendering-srv/blob/master/docs/modules/ROOT/assets/images/fonts.png[fonts.png].

[#usage]
== Usage

[#usage_running_as_container]
=== Running as Container

[source,sh]
----
docker run -e NODE_ENV=production -d -p 50051:50051 -n pdf-rendering-srv ghcr.io/restorecommerce/pdf-rendering-srv
----

or

[source,sh]
----
docker run -d -p 50051:50062 -n pdf-rendering-srv ghcr.io/restorecommerce/pdf-rendering-srv
----

[#example_calls]
=== Example calls

These examples use the link:https://github.com/fullstorydev/grpcurl[grpcurl] CLI tool to make gRPC calls.

[#example_call_from_url]
==== From URL

Produces a PDF file called `out.pdf`

[source,sh]
----
grpcurl -plaintext -d '{
  "individual": {
    "data": [
      {
        "data": {
          "source": {
            "url": "https://en.wikipedia.org/wiki/WebKit"
          }
        }
      }
    ]
  }
}' 127.0.0.1:50051 io.restorecommerce.pdf_rendering.PdfRenderingService.Render | jq -r '.individual.RenderingResponse[0].payload.pdf.data' | base64 -d > out.pdf
----

[#example_call_from_html]
==== From HTML

Produces a PDF file called `out.pdf`

[source,sh]
----
grpcurl -plaintext -d '{
  "individual": {
    "data": [
      {
        "data": {
          "source": {
            "html": "Hello World"
          }
        }
      }
    ]
  }
}' 127.0.0.1:50051 io.restorecommerce.pdf_rendering.PdfRenderingService.Render | jq -r '.individual.RenderingResponse[0].payload.pdf.data' | base64 -d > out.pdf
----

[#example_call_combine]
==== Combine Multiple PDFs

Produces a PDF file called `combined.pdf`

[source,sh]
----
grpcurl -plaintext -d '{
  "combined": {
    "data": [
      {
        "source": {
          "url": "https://en.wikipedia.org/wiki/WebKit"
        }
      },
      {
        "source": {
          "html": "Hello World"
        }
      }
    ]
  }
}' 127.0.0.1:50051 io.restorecommerce.pdf_rendering.PdfRenderingService.Render | jq -r '.combined.payload.pdf.data' | base64 -d > combined.pdf
----

[#example_s3]
==== Upload directly to S3

Produces a PDF file and uploads it to the `pdf` bucket at the `sample.pdf` key.

[source,sh]
----
grpcurl -plaintext -d '{
  "individual": {
    "data": [
      {
        "data": {
          "source": {
            "html": "Hello World"
          }
        },
        "output": {
          "metaData": {
            "title": "Replacement Title",
            "creator": "Replacement Creator",
            "producer": "Replacement Producer"
          },
          "uploadOptions": {
            "bucket": "pdf",
            "key": "sample.pdf"
          }
        }
      }
    ]
  }
}' 127.0.0.1:50051 io.restorecommerce.pdf_rendering.PdfRenderingService.Render | jq
----

[#customization]
== Customization

[#customization_install_additional_fonts]
=== Installing Additional Fonts

See the Dockerfile how fonts are installed in Alpine Linux.

[#configuration]
== Configuration

All configuration options and their defaults are available in `./cfg/config.json`.

[#api]
== API

This microservice exposes the following gRPC endpoints:

[#api_info]
=== Info

Return data about the used chromium instance.

`io.restorecommerce.pdf_rendering.PdfRenderingService.Info`

[#api_render]
=== Render

Render provided request into a PDF.

`io.restorecommerce.pdf_rendering.PdfRenderingService.Render`

[width="100%",cols="20%,16%,20%,44%",options="header",]
|==========================================================================================================================
|Field |Type |Label |Description
|individual |`io.restorecommerce.pdf_rendering.IndividualRequest` |optional |Individual render request
|combined |`io.restorecommerce.pdf_rendering.CombinedRequest` |optional |Combined render request
|subject |`io.restorecommerce.auth.Subject` |optional |Subject details
|==========================================================================================================================

For details of the meaning of these options check the link:https://pptr.dev/api/puppeteer.pdfoptions[PDFOptions interface] of Puppeteer.

