name: Release

on:
  push:
    branches:
      - master
  workflow_dispatch:

permissions:
  contents: read

jobs:
  release:
    permissions:
      contents: write
      issues: write
      pull-requests: write
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
        with:
          ref: master

      - uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}

      - uses: docker/setup-buildx-action@v3
        with:
          install: true

      - name: Set variables
        id: vars
        run: |
          echo ::set-output name=repo_name::$(echo ${GITHUB_REPOSITORY#*/*})

      - uses: docker/metadata-action@v5
        id: docker_meta
        with:
          images: ${{ github.repository }}

      - uses: docker/build-push-action@v5
        with:
          load: true
          tags: ${{ github.repository }}
          labels: ${{ steps.docker_meta.outputs.labels }}

      - name: Install Dependencies
        run: npm i --no-save @semantic-release-plus/docker

      - run: npx semantic-release@22.0.12
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: upgrade-services.yaml
          ref: master
          repo: restorecommerce/charts
          token: "${{ secrets.CHARTS_WORKFLOW_TOKEN }}"